[package]
name = "problem"
version = "0.1.0"
authors = ["kamedon <hkamei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lang-lib = { path = "../lang-lib" }